# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

$:.push File.expand_path("../lib", __FILE__)
require "devise_crowd_authenticatable/version"

Gem::Specification.new do |s|
  s.name     = 'devise_crowd_authenticatable'
  s.version  = DeviseCrowdAuthenticatable::VERSION.dup
  s.platform = Gem::Platform::RUBY
  s.summary  = 'Devise extension to allow authentication via CROWD'
  s.email = 'parmargk@gmail.com'
  s.homepage = 'https://github.com/parmarg/devise_crowd_authenticatable'
  s.description = s.summary
  s.authors = ['Gurp Parmar']

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  s.add_dependency('devise', '~> 2.0')
  s.add_dependency('crowd-client', '~> 0.1.5')

  s.add_development_dependency('rake', '>= 0.9')
  s.add_development_dependency('rdoc', '>= 3')
  s.add_development_dependency('rails', '~> 3.2')
  s.add_development_dependency('sqlite3')
  s.add_development_dependency('ruby-prof')
  s.add_development_dependency('factory_girl_rails', '~> 1.0')
  s.add_development_dependency('factory_girl', '~> 2.0')
  s.add_development_dependency('rspec-rails')

  %w{database_cleaner capybara launchy autotest-rails ZenTest autotest-growl}.each do |dep|
    s.add_development_dependency(dep)
  end
end

